name: Format
on: push
jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    concurrency:
      group: ${{ github.workflow }}-{{ $github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: format
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 2.1.0
          args: --check .
